stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bots-ffl-midwest:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: 1450
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./midwest-dc.yaml